version: '3'
services:

  ## Router
  router:
    image: mongo:${mongoVersion}
    container_name: router
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017 --bind_ip_all
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./scripts:/scripts

  ## Config Servers
  configsvr01:
    image: mongo:${mongoVersion}
    container_name: configsvr01
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
    ports:
      - 27119:27017
    restart: always
    links:
      - shard01-a
      - shard02-a
  configsvr02:
    image: mongo:${mongoVersion}
    container_name: configsvr02
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
    ports:
      - 27120:27017
    restart: always
    links:
      - configsvr01

  ## Shards
  ## Shards 01

  shard01-a:
    image: mongo:${mongoVersion}
    container_name: shard01-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
    ports:
      - 27122:27017
    restart: always
    links:
      - shard01-b
      - shard01-c
  shard01-b:
    image: mongo:${mongoVersion}
    container_name: shard01-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
    ports:
      - 27123:27017
    restart: always
  shard01-c:
    image: mongo:${mongoVersion}
    container_name: sshard01-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
    ports:
      - 27124:27017
    restart: always

  ## Shards 02
  shard02-a:
    image: mongo:${mongoVersion}
    container_name: shard02-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
    ports:
      - 27125:27017
    restart: always
    links:
      - shard02-b
      - shard02-c
  shard02-b:
    image: mongo:${mongoVersion}
    container_name: shard02-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
    ports:
      - 27126:27017
    restart: always
  shard02-c:
    image: mongo:${mongoVersion}
    container_name: shard02-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
    ports:
      - 27127:27017
    restart: always
